# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12registration.proto\x12\x0cregistration\"@\n\rInsertRequest\x12\x14\n\x0cNumber_plate\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\"0\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x0e\n\x0c\x46\x65tchRequest\">\n\rFetchResponse\x12-\n\x0c\x64\x61ta_entries\x18\x01 \x03(\x0b\x32\x17.registration.DataEntry\"<\n\tDataEntry\x12\x14\n\x0cNumber_plate\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\"%\n\rDeleteRequest\x12\x14\n\x0cNumber_plate\x18\x01 \x01(\t\"0\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"S\n\rUpdateRequest\x12\x14\n\x0cNumber_plate\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x11\n\tcondition\x18\x04 \x01(\t\"0\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa6\x02\n\x13registrationService\x12\x43\n\x06Insert\x12\x1b.registration.InsertRequest\x1a\x1c.registration.InsertResponse\x12@\n\x05\x46\x65tch\x12\x1a.registration.FetchRequest\x1a\x1b.registration.FetchResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.registration.DeleteRequest\x1a\x1c.registration.DeleteResponse\x12\x43\n\x06Update\x12\x1b.registration.UpdateRequest\x1a\x1c.registration.UpdateResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSERTREQUEST._serialized_start=36
  _INSERTREQUEST._serialized_end=100
  _INSERTRESPONSE._serialized_start=102
  _INSERTRESPONSE._serialized_end=150
  _FETCHREQUEST._serialized_start=152
  _FETCHREQUEST._serialized_end=166
  _FETCHRESPONSE._serialized_start=168
  _FETCHRESPONSE._serialized_end=230
  _DATAENTRY._serialized_start=232
  _DATAENTRY._serialized_end=292
  _DELETEREQUEST._serialized_start=294
  _DELETEREQUEST._serialized_end=331
  _DELETERESPONSE._serialized_start=333
  _DELETERESPONSE._serialized_end=381
  _UPDATEREQUEST._serialized_start=383
  _UPDATEREQUEST._serialized_end=466
  _UPDATERESPONSE._serialized_start=468
  _UPDATERESPONSE._serialized_end=516
  _REGISTRATIONSERVICE._serialized_start=519
  _REGISTRATIONSERVICE._serialized_end=813
# @@protoc_insertion_point(module_scope)
